language: node_js
node_js:
- 6
- 5
- 4
install:
- npm install
script:
- npm run lint
- npm run nsp
deploy:
  provider: npm
  email: billing.relate@schibsted.media
  on:
    branch: master
    node: '6'
  api_key:
    secure: Ik2oB60Fl9rIG9ABuGAaVtXa6zOfm+X317ZZncmiRV29rvoLzkgx/MkbQYTRFqK/XR3qrWVJCuLCZoUwm8pv0Y8knSZo008+q+Qu2//eCbO6k8B8F0tYENd88s2+Ma2P+gXn5XKlV8GuBHN6Eop+BqIGpw00Q4yS6f14p4hcNNFu4sDqwZsbykKpuEndhGUenoPE+YOX4+bs7G0vKULmsjohFy/KulaS/KY/Wbhnc8jI5EiRFb/PL5iI/bgT+tgzi+Mg/RS/P50MecyF+kKcNpjFAaXo8Ipb6odL9NTdmKU1UgHPgXmpy7ySdvRAicyuZCb+WP4ETNxHHuy3oP7HAgIgIR3pUX6XIX5/zOlwH9yH+YbzP2rYwfNfSHJ4nupPx1t2qHfdVoUaKrlfFosYYF8cTrfYm1Y15XDMv0b1elYj/Tn2A2jXZixt+pcs1MoqKIvMRqUAjEqFrxMqJYGk14ghRi8eUqSb2vxtIqWoByVY4e7f+BcCvEPlTkxOANCGa6hrViQAgI5RgogOzo9hfpGScomsdNCgJFtAM4kwOCjB8ge4EK4ZMoX2t6IvRQyg/6JgvzcyQyEtAa4PCf9blf8XAtJMFSEn5blX+0NpTKpv0ef9IUh0tn0jf6VJIGMQtMHaldavdBJASo8EyEnq9w2xYdqzujVajR70WAZOyCA=
